project_id = "skmignrszbhntcljenxq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
sender_url = "http://127.0.0.1:54325"
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MB"
image_transformation = true

[auth]
enabled = true
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.purchase-ticket]
verify_jwt = true

[functions.spotify-genre-analytics]
verify_jwt = true

[edge-runtime]
enabled = true
policy = "per_request"
inspector_port = 8083