// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skmignrszbhntcljenxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrbWlnbnJzemJobnRjbGplbnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTQxNTksImV4cCI6MjA3MjQ5MDE1OX0.uhwprc5EY0dxTiL8TWnrWYrz3t-Cjoa7BxjuazDMwXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});